Dashboard v0.01
labs-vision/Karyakram-frontend pull request #15
Opened 2022-01-22 09:55 UTC by ChiragSaxena5437

A very basic dashboard design with minimalistic features.

2022-01-22 10:08 UTC, rakshit087 requested changes
Bro, please pull the latest changes  before PR xD. 
Or ek baar Pulkit ko dekhne dete

2022-01-22 10:08 UTC, rakshit087 commented on src/App.js
> -import Sidebar from "./components/Sidebar";
Don't rmove the sidebar please xD

2022-01-22 10:13 UTC, pulkitvyas08 reviewed
Why is there a submodule?

2022-01-22 10:13 UTC, pulkitvyas08 commented on package.json
> +  "name": "karyakaram",
Wrong name, the name is `karyakram` don't change it

2022-01-22 10:13 UTC, pulkitvyas08 commented on package.json
> -    "react-router-dom": "^6.2.1",
Pull the changes first. @rakshit087 has added router stuff

2022-01-22 10:13 UTC, pulkitvyas08 commented on src/App.css
> -.App {
Why delete this?

2022-01-22 10:13 UTC, pulkitvyas08 commented on src/App.js
> -import Sidebar from "./components/Sidebar";
+1

2022-01-22 10:13 UTC, pulkitvyas08 commented on src/App.test.js
> +import { render, screen } from '@testing-library/react';
We don't need this atm

2022-01-22 10:14 UTC, pulkitvyas08 requested changes
@ChiragSaxena5437 Quite a few issues here. As @rakshit087 has said, please pull all the changes first then add your stuff or resolve the conflicts

2022-01-23 02:11 UTC, ChiragSaxena5437 commented
Ok, all the changes made in a new PR.

2022-01-23 02:11 UTC, closed without merging