feat(global): added light and dark themes
labs-vision/Karyakram-Frontend pull request #23
Opened 2022-03-02 18:05 UTC by rakshit087

We can extend this component with colors, also a media query can be used to auto update the theme.

2022-03-02 18:14 UTC, pulkitvyas08 requested changes

2022-03-02 18:14 UTC, pulkitvyas08 commented on src/App.tsx
>  function App() {
Convert this to an arrow function

2022-03-02 18:14 UTC, pulkitvyas08 commented on src/App.tsx
> +    <ThemeProvider theme={darkTheme}>
Are we really going for this? Will this make #3 difficult to implement?

2022-03-02 18:15 UTC, pulkitvyas08 commented
@rakshit087 Are you doing Varcel or should I?

2022-03-02 18:27 UTC, rakshit087 commented on src/App.tsx
> +    <ThemeProvider theme={darkTheme}>
I thought it’s the same thing. Material has some great defaults for dark theme and all we need to do is toggle a state in order to switch mode.
https://mui.com/customization/dark-mode/

2022-03-02 18:28 UTC, rakshit087 commented
> @rakshit087 Are you doing Varcel or should I?

Yes please do :))

2022-03-02 19:34 UTC, pulkitvyas08 commented on src/App.tsx
> +    <ThemeProvider theme={darkTheme}>
Ohkay makes sense so we can use the state that they would provide. Great then go ahead!

2022-03-02 19:34 UTC, pulkitvyas08 commented
> > @rakshit087 Are you doing Varcel or should I?
> 
> Yes please do :))

Will do!

2022-03-03 08:00 UTC, pulkitvyas08 approved these changes

2022-03-03 08:00 UTC, merged